### ISSUE TITLE
Getting invalid string value from notification intent. 

### ISSUE THREAD

**Issue by milan-galitein** [wonderpush/wonderpush-android-sdk#12]
Today suddenly stop working notification due to invalid string data. 

We are sending string value from server but getting inside double quote in notification intent. 

We are using 4.4.0

```
implementation 'com.wonderpush:wonderpush-android-sdk:4.4.0'
implementation 'com.wonderpush:wonderpush-android-sdk-fcm:1.0.7'
```

Here is sample notification intent data. 
![image](https://github.com/wonderpush/wonderpush-android-sdk/assets/46750938/b6dfa49c-daac-48d1-9474-7105fdd221cc)

Please help asap because it's affecting our many live users.

**Comment by ofavre** [comment]
Hi,

This is a recent change on our server-side components, not related to the WonderPush Android SDK.
You have contacted us using the chat on your WonderPush dashboard, thank you for that, we'll tell you shortly when this is fixed.
