### ISSUE TITLE
Support notification icon 'accent color'

### ISSUE THREAD

**Issue by Zizaco** [wonderpush/wonderpush-android-sdk#2]
Currently, there is no way of specifying the notification accent color:

![image](https://user-images.githubusercontent.com/777635/43520843-6a2b606e-9594-11e8-88a4-46577b023380.png)

I suggest adding support to a manifest meta-data field kinda like "wonderpushNotificationIcon"
```gradle
android {
    defaultConfig {
        applicationId 'YOUR_PACKAGE' //
        manifestPlaceholders = [
                wonderpushDefaultActivity:  'YOUR_MAIN_ACTIVITY_CLASS',
                wonderpushNotificationIcon: 'YOUR_NOTIFICATION_ICON'
                wonderpushNotificationAccent: '#00BDCC' // <----- here
        ]
    }
}
```

**Comment by ofavre** [comment]
There was no way do specify a default accent color but you can set one when sending notifications, you're right.
The v3 that we are about to release does support this. Checkout the documentation and follow releases either on GitHub or [our community forum](https://discuss.wonderpush.com/c/announcements).
