### ISSUE TITLE
Targeting specific android channels

### ISSUE THREAD

**Issue by condesales** [wonderpush/wonderpush-android-sdk#3]
I'm creating a channel using `WonderPushChannel` utility class like this:

```kotlin
val channel = WonderPushChannel(context.getString(channelId), group.id)
channel.name = context.getString(channelName)
```
and then adding it to a group: 
```kotlin
val group = WonderPushChannelGroup(groupId)
WonderPushUserPreferences.putChannel(channel, group))
```
This creates a channel in that group in the system notification settings page, just as I expected.

I'm also adding that channel id into the installation custom properties using:
``` kotlin
WonderPush.putInstallationCustomProperties()
```
---
When creating a new notification via the dashboard, I'm then selecting that channel id as target using 
![image](https://user-images.githubusercontent.com/1881318/48428130-3cf06980-e762-11e8-9147-c3da94ad3937.png)

The behaviour I was expecting was that for users that have disabled that especific channel via the system notification settings page the push wouldn't show up.

What am I doing wrong? How can I specify the channel for a push sent via dashboard?

**Comment by ofavre** [comment]
Hi Felipe,

`WonderPush.putInstallationCustomProperties()` enables you to store custom data of your choosing inside the installation, to later segment on it. It's in no way actively linked to anything like Android Channel user preferences.

**Comment by condesales** [comment]
@ofavre 
Could you not potentially add the custom properties to the payload you send to FCM?
something like:
```json
{
 "to" : "<fcm-device-token>",
 "notification" : {
     "android_channel_id" : ["custom_property1", "custom_property2" ,"custom_property3"],
     "body" : "Body of Your Notification",
     "title": "Title of Your Notification"
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title",
     "key_1" : "Value for key_1",
     "key_2" : "Value for key_2"
 }
}
```
I was playing around sending the messages myself using `https://fcm.googleapis.com/fcm/send` and adding 
`"android_channel_id" : ["custom_property1", "custom_property2" ,"custom_property3"]` does the trick

**Comment by ofavre** [comment]
We do not use FCM's specific format but rather handle the notification formating ourself in order to better control the full breadth of feature exposed by the [Notification.Builder](https://developer.android.com/reference/android/app/Notification.Builder).
You can take a look at our [Notification format reference](https://wonderpush-management-api.readme.io/docs/notification), especially `alert.android.` keys.
You can add anything that will end-up in the `data` field of your snippet by using the `push.payload` field.
