### ISSUE TITLE
Receiver for advanced click handling is not reliably triggered

### ISSUE THREAD

**Issue by cocktailkrabbe** [wonderpush/wonderpush-android-sdk#4]
Hi,

as described in your documentation under "[advanced click handling](https://docs.wonderpush.com/docs/advanced-click-handling#section-handling-click-broadcasts)", I implemented a receiver to open the URL within the existing webview in the app.

This works great as long as the app is closed before. Once the app is open in the background, receiving a push message only brings the app to the front without triggering the receiver.

The receiver is registered in the "onCreate" method in the application class.

```java
public class Application extends android.app.Application {

    @Override
    public void onCreate() {
        super.onCreate();

        [...]

        if (BuildConfig.NOTIFICATIONS_ENABLED) {
            WonderPush.initialize(this);

            LocalBroadcastManager.getInstance(this).registerReceiver(new BroadcastReceiver() {
                @Override
                public void onReceive(Context context, Intent intent) {

                    if (!WonderPush.INTENT_NOTIFICATION_WILL_OPEN_EXTRA_NOTIFICATION_TYPE_DATA.equals(
                            intent.getStringExtra(WonderPush.INTENT_NOTIFICATION_WILL_OPEN_EXTRA_NOTIFICATION_TYPE))) {

                        Intent pushNotif = intent.getParcelableExtra(WonderPush.INTENT_NOTIFICATION_WILL_OPEN_EXTRA_RECEIVED_PUSH_NOTIFICATION);

                        if (pushNotif.hasExtra("custom")) {
                            try {
                                JSONObject customData = new JSONObject(pushNotif.getExtras().getString("custom"));

                                openNotificationURL(customData.getString("url"));

                            } catch (JSONException e) {

                            }
                        }
                    }
                }
            }, new IntentFilter(WonderPush.INTENT_NOTIFICATION_WILL_OPEN));
        }
```

**Comment by ofavre** [comment]
Hi,

I've tested with automatic SDK initialization _disabled_ and registering the listener _after_ initializing the SDK like you did, but cannot reproduce.
Can you look at the extras you find using this?

```java
Bundle extras = pushNotif.getExtras();
extras.isEmpty(); // unparcels the bundle
Log.e("YourApp", "extras: " + extras);
```

What you say is that you don't always get the same extras whether the application was quit (swiped up from the task list), or running either in foreground or background.
If that's confirmed, can you provide a reproduction project so I can move forward in identifying the error?

**Comment by cocktailkrabbe** [comment]
I'm sorry for not answering for such a long time.
After a bunch of tests and debugging hours, I can confirm that your SDK performs right.
Meanwhile we've fixed the error in our application code.

Thank you for your guidance!
