### ISSUE TITLE
Gradle build issue caused by cyclic dependency

### ISSUE THREAD

**Issue by brudaswen** [wonderpush/wonderpush-android-sdk#6]
The latest `wonderpush-android-sdk:3.4.0` has a dependency to `wonderpush-android-sdk-fcm:1.0.0` and vice versa. This causes issues for our gradle build.

- `com.wonderpush:wonderpush-android-sdk:3.4.0`.
- Gradle `5.5.1` and `6.5.1`.

```
* What went wrong:
Execution failed for task ':app:getDependencies'.
> java.lang.StackOverflowError (no error message)
```

We are currently excluding the recursive dependency as a workaround:
```
implementation('com.wonderpush:wonderpush-android-sdk:3.4.0') {
    exclude group: 'com.wonderpush', module: 'wonderpush-android-sdk'
}
```

**Comment by ofavre** [comment]
Hi,

Gradle compiles the SDK and implementing applications fine.
Running `./gradlew :app:dependencies` run fine too.
Your plugin or custom code that declared the `getDependencies` task however seems to not follow. You should open a ticket on their project.

**Comment by ofavre** [comment]
As of v4.0.0 we have removed this cyclic dependency.
I was not able to reproduce, probably because I don't have the same Gradle plugin that analyses the dependencies.
