### ISSUE TITLE
App Crashes But Can Receive Notifications

### ISSUE THREAD

**Issue by furkan6116** [wonderpush/wonderpush-android-sdk#7]
hi. ı installed cordova plugin. my app crashes but ı can still get notifications

**Comment by ofavre** [comment]
Hi,

Can you please open a ticket on the [wonderpush/wonderpush-cordova-sdk](https://github.com/wonderpush/wonderpush-cordova-sdk/issues) project instead?
A reproduction project for your issue would also be really helpful.
